# Generated by Django 4.2.5 on 2023-09-12 01:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_aluno2_delete_aluno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno2',
            new_name='Aluno',
        ),
    ]
